USE master;
ALTER DATABASE SQL_EXCERCISES_WEEK_THREE_LAB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE SQL_EXCERCISES_WEEK_THREE_LAB;
GO


CREATE DATABASE SQL_EXCERCISES_WEEK_THREE_LAB;
USE SQL_EXCERCISES_WEEK_THREE_LAB;
GO


DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
    accNo CHAR(12) PRIMARY KEY,
    accountType VARCHAR(20) NOT NULL,
    customer VARCHAR(100) NOT NULL,
    balance DECIMAL(10, 2),
    CHECK (balance>=0)
);
GO


INSERT INTO ACCOUNT
VALUES ('6123-1234567', 'Award Saver', 'Peter Wang', 12234.94);
INSERT INTO ACCOUNT
VALUES ('0231-2342142', 'Cheque', 'Mary Alison', 5342.98);
INSERT INTO ACCOUNT
VALUES ('8232-3231134', 'NetSaver', 'Ally Kent', 23112.33);
INSERT INTO ACCOUNT
VALUES ('6123-1234568', 'Cheque', 'Peter Wang', 231.31);
GO

SELECT customer
FROM ACCOUNT
WHERE accNo = '6123-1234568';

SELECT *
FROM ACCOUNT;

SELECT *
FROM ACCOUNT
WHERE (balance>5000);

SELECT accNo
FROM ACCOUNT
WHERE (customer='Peter Wang');

SELECT *
FROM ACCOUNT
WHERE (accountType='Cheque') AND (balance>1000);

SELECT *
FROM ACCOUNT
WHERE (customer='Ally Kent') OR (customer='Peter Wang');

UPDATE ACCOUNT
SET balance = (balance+100)
WHERE (accNo='0231-2342142');

SELECT *
FROM ACCOUNT
WHERE (accNo='0231-2342142');

DELETE ACCOUNT
WHERE (customer='Ally Kent');
SELECT *
FROM ACCOUNT;